version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test-curiousqa:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Setup pipenv
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            echo $PIPENV_PIPFILE
            pipenv --venv
          environment:
            PIPENV_PIPFILE src/curiousqa/Pipfile
      - run:
          name: Run curiousqa Python Test
          command: pipenv run python src/curiousqa/manage.py test
          #name: Test

workflows:
  main:
    jobs:
      - build-and-test-curiousqa
